# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-11-09 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20201107_2207'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table=None,
        ),
        migrations.AlterModelTable(
            name='articlecategory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='label',
            table=None,
        ),
    ]
