# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-19 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190919_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
        migrations.AlterField(
            model_name='article',
            name='index_image',
            field=models.CharField(max_length=300, null=True, verbose_name='文章主图'),
        ),
    ]
