# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-25 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='describe',
            field=models.TextField(default='', verbose_name='文章描述'),
        ),
    ]
