# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-25 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_describe'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='describe',
            field=models.CharField(default='', max_length=100, verbose_name='类别描述'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='image_url',
            field=models.CharField(default='', max_length=100, verbose_name='类别图片'),
        ),
    ]
