# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-27 04:17
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190925_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='describe',
            field=models.TextField(default='', help_text='用于列表页展示文章简介', verbose_name='文章描述'),
        ),
    ]
