# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-29 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='article',
            new_name='articles',
        ),
    ]
