# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-01 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20190929_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='labels',
            field=models.ManyToManyField(to='article.Label', verbose_name='文章标签'),
        ),
    ]
