# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-19 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20191023_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='index_image',
            field=models.URLField(null=True, verbose_name='文章主图'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='describe',
            field=models.CharField(default='', help_text='不超过100个字', max_length=100, verbose_name='类别描述'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='image_url',
            field=models.URLField(null=True, verbose_name='类别图片'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='name',
            field=models.CharField(help_text='不超过10个字', max_length=10, verbose_name='名称'),
        ),
    ]
