# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-19 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20191119_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='index_image',
            field=models.CharField(max_length=1000, null=True, verbose_name='文章主图'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='image_url',
            field=models.CharField(max_length=1000, null=True, verbose_name='类别图片'),
        ),
    ]
