# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-20 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20191119_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='b不超过50字', max_length=50, verbose_name='标题'),
        ),
    ]
