# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-06 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20191120_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='name',
            field=models.CharField(help_text='不超过20个字', max_length=20, verbose_name='名称'),
        ),
    ]
