# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-19 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(help_text='不能超过20个字', max_length=20, verbose_name='公告标题')),
                ('content', models.CharField(help_text='不能超过500个字', max_length=500, verbose_name='公告内容')),
                ('is_up', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('read_count', models.IntegerField(default=0, verbose_name='阅读数')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'db_table': 'notice',
            },
        ),
    ]
