# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-11-09 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_notice_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notice',
            table=None,
        ),
    ]
