# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-29 09:35
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_auto_20190928_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='不能超过500个字', max_length=500, verbose_name='公告内容'),
        ),
    ]
