# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-29 23:37
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_auto_20190929_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='不能超过300个字', max_length=300, verbose_name='公告内容'),
        ),
    ]
