# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-01 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_carousel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='标题'),
        ),
    ]
