# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-19 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_carousel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image_url',
            field=models.URLField(verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='url',
            field=models.URLField(verbose_name='指向地址'),
        ),
    ]
