# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-19 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20191119_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image_url',
            field=models.CharField(max_length=1000, verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='url',
            field=models.CharField(max_length=1000, verbose_name='指向地址'),
        ),
    ]
