# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-20 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='', max_length=200, verbose_name='个人简介'),
        ),
        migrations.AddField(
            model_name='user',
            name='soliloquy',
            field=models.TextField(default='', verbose_name='独白'),
        ),
    ]
