# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-25 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190920_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(max_length=30, verbose_name='职业'),
        ),
    ]
