# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-25 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190925_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='webname',
            field=models.CharField(default='', max_length=20, verbose_name='网名'),
        ),
    ]
