# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-19 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191119_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(max_length=1000, null=True, verbose_name='用户头像路径'),
        ),
    ]
