# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-19 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20190928_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(help_text='必须以http/https开头', verbose_name='链接'),
        ),
    ]
