# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-20 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_auto_20191119_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(help_text='不超过20字', max_length=20, verbose_name='名字'),
        ),
    ]
