# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-22 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='内容')),
            ],
            options={
                'verbose_name': '鸡汤',
                'verbose_name_plural': '鸡汤',
                'db_table': 'soup',
            },
        ),
    ]
