# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-19 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soup',
            name='content',
            field=models.CharField(help_text='不超过50字', max_length=50, verbose_name='内容'),
        ),
    ]
