# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-11-07 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(help_text='No more than 50 characters', max_length=50, verbose_name='照片标题')),
                ('url', models.CharField(max_length=255, null=True, verbose_name='照片地址')),
                ('thumbnail_url', models.URLField(max_length=255, null=True, verbose_name='缩略图')),
            ],
            options={
                'verbose_name': '照片',
                'verbose_name_plural': '照片',
                'db_table': 'photos',
            },
        ),
        migrations.CreateModel(
            name='PhotoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(help_text='不超过50个字', max_length=50, verbose_name='相册类名')),
                ('is_secret', models.BooleanField(default=False, verbose_name='是否秘密的')),
            ],
            options={
                'verbose_name': '相册类别',
                'verbose_name_plural': '相册类别',
                'db_table': 'photo_category',
            },
        ),
        migrations.CreateModel(
            name='PhotoGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=50, verbose_name='组名')),
                ('index_image', models.URLField(help_text='https或http开头', max_length=255, verbose_name='主图url')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='photo.PhotoCategory')),
            ],
            options={
                'verbose_name': '相册组',
                'verbose_name_plural': '相册组',
                'db_table': 'photo_group',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photo.PhotoGroup'),
        ),
    ]
