# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-11-09 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='photocategory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='photogroup',
            table=None,
        ),
    ]
