# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-04 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20190928_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(help_text='No more than 10 characters', max_length=10, verbose_name='照片标题'),
        ),
    ]
