# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-20 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20191119_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocategory',
            name='name',
            field=models.CharField(help_text='不超过10个字', max_length=10, verbose_name='相册类名'),
        ),
    ]
