# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-06 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_auto_20191120_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='photocategory',
            name='is_secret',
            field=models.BooleanField(default=False, verbose_name='是否秘密的'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(max_length=1000, null=True, verbose_name='照片地址'),
        ),
    ]
