# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-11-06 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_auto_20191206_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=50, verbose_name='组名')),
                ('index_image', models.URLField(help_text='https或http开头', max_length=255, verbose_name='主图url')),
            ],
            options={
                'verbose_name': '相册组',
                'verbose_name_plural': '相册组',
                'db_table': 'photo_group',
            },
        ),
        migrations.RemoveField(
            model_name='photo',
            name='category',
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail_url',
            field=models.URLField(max_length=255, null=True, verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(help_text='No more than 50 characters', max_length=50, verbose_name='照片标题'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(max_length=255, null=True, verbose_name='照片地址'),
        ),
        migrations.AlterField(
            model_name='photocategory',
            name='name',
            field=models.CharField(help_text='不超过50个字', max_length=50, verbose_name='相册类名'),
        ),
        migrations.AddField(
            model_name='photogroup',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='photo.PhotoCategory'),
        ),
        migrations.AddField(
            model_name='photo',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photo.PhotoGroup'),
        ),
    ]
